### PR TITLE
Automatically open card modal based on the URL

### PR DESCRIPTION
**Pull request by cassiomarques**
This PR adds the following features:

- Updates the URL hash when a card is opened
- If the initial URL has a valid hash, automatically open the card modal.

card-link

For some reason I was having weird errors when trying to run the ClojureScipt tests. I decided to change how some of the JavaScript code is loaded and make it possible to run these tests through `lein cljsbuild test`. In a future PR I'll remove the ClojureScript tests from the browser and make it possible to run then with `autotest` from the command line.

### CODE REVIEW

**Comment by cassiomarques** [comment]
@emfigo @andistuder @timstott @johnwake @jamesmarkcook please :eyes: !

**Comment by jamesmarkcook** [comment]
I'm not one to be judging your Clojure @cassiomarques but all looks good to me :blush:

You must let me know what you use to create those fancy GIFs :+1:

**Comment by johnwake** [comment]
LGTM @cassiomarques Nice changes :+1: :bow: 

:memo: Now i've pulled the OAuth changes i will have a play around locally.

**Comment by cassiomarques** [comment]
@jamesmarkcook I use this app: https://itunes.apple.com/us/app/picgif-lite/id844918735?mt=12

You need to record your screen using Quicktime and then use PicGif to create the gif. The default number of frames is too low, usually I change it to something between 100 and 200, depending on the length of the original video :smiley:

**Comment by cassiomarques** [comment]
@johnwake Thanks, do let me know if you find any :bug: :bee: :beetle: !

**Pull request merged**
